### ISSUE TITLE
Don't change if no _args

### ISSUE THREAD

**Issue by atypicalprogrammer** [juanjoDiaz/removeNPMAbsolutePaths#1]
Please don't change the file if the _args is not present. Right now, every time removeNPMAbsolutePaths is ran, the file is rewritten.

**Comment by juanjoDiaz** [comment]
It's not only the _args field. The _where field also contain the absolute path.

What removeNPMAbsolutePaths actually does is remove all the fields that are internal for npm (all the fields starting with "_").

I could rewrite the file only if it contains fields starting with "_". Will that be ok?

**Comment by atypicalprogrammer** [comment]
Yes, rewriting only if it contains fields starting with _ makes much sense!  :-) thx

**Comment by atypicalprogrammer** [comment]
Thanks :-)

**Comment by juanjoDiaz** [comment]
You're welcome 😊
