### ISSUE TITLE
1.0.5 does not work on old node versions

### ISSUE THREAD

**Issue by medzes** [juanjoDiaz/removeNPMAbsolutePaths#11]
Hello juanjoDiaz,

I ran into a syntax error with version 1.0.5 with production old node version, I expect it is the same issue as reported earlier for 1.0.0, a comma at the end of the function call.

Version 1.0.4 works fine for me on old node.

Can you remove the comma at the end of line 71 in removeNPMAbsolutePaths.js ?

**Comment by juanjoDiaz** [comment]
Fixed in 1.0.6.

However, Node 6 reached its end of life on April 30, 2019. So it's not advisable to continue using it.
