### ISSUE TITLE
Is this package necessary for recent versions of npm?

### ISSUE THREAD

**Issue by bricker** [juanjoDiaz/removeNPMAbsolutePaths#27]
I came across this package in https://github.com/github/codeql-action while I was researching best practices for checking in `node_modules` to git. I had never heard of this issue with absolute paths, so I checked to see it for myself. What I found is that after running either `npm install` or `npm ci`, no file in `node_modules` reference any local paths, nor do they contain the `_args`, `_where`, etc. internal properties.

So my question is: **Am I missing something, or is this package no longer necessary for recent versions of npm?**

Some commands I ran to check:

```bash
# Look for references to my local username in node_modules (recursive)
$ grep -r "bricker" node_modules # empty

# Look for references to internal property `_where` package.json files (recursive)
$ grep -r "_where" node_modules/**/package.json # empty

# Look for lines containing `"/` (some string starting with a path separator, possibly indicating an absolute path) in package.json files (recursive)
$ grep -r "\"/" node_modules/**/package.json # no system paths
```

I'm running the following versions:

- node 16.14.0
- npm 8.3.1

**Comment by juanjoDiaz** [comment]
Indeed, it seems that the issue have been corrected in newest versions of npm
