### ISSUE TITLE
How to deal with the absolute path uploaded when running npm publish?

### ISSUE THREAD

**Issue by wll8** [juanjoDiaz/removeNPMAbsolutePaths#30]
This repository probably doesn't have a way to handle this situation, but do you have any interesting suggestions? thanks.

**Comment by wll8** [comment]
``` sh
>node -v
v14.15.5

>npm -v
8.15.1
```

The problem persists with higher npm versions

- https://github.com/npm/npm/issues/20797
- https://github.com/zkat/pacote/issues/153
- https://github.com/npm/npm/issues/10393#issuecomment-173221538

**Comment by juanjoDiaz** [comment]
Hi @wll8 ,

I need more details of what are you doing exactly and where are you getting the `_from` property (in your package.json, in the lock file, ...)

This library cleans up the package.json files in a folder recursively.
So you could run it as some point before publishing to remove those `_from` properties.
